apiVersion: batch/v1
kind: CronJob
metadata:
  name: callout
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: callout
              image: buildpack-deps:curl
              args:
                - /bin/sh
                - -ec
                - curl http://my-node-service:3000
          restartPolicy: Never